title: RNP
description: C library approach to OpenPGP; GnuPG alternative.
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

tagline: >-
  High performance<br>C++ OpenPGP library

pitch: >-
  Compatible GnuPG alternative, fully compliant to RFC 4880.

author: "Ribose Inc."

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/software/rnp/docs/README/", title: "Get Started" }

permalink: /blog/:month-:day-:year/:title/
